//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alimenterre3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<CategoryUser> UserCategories { get; set; }
        public virtual DbSet<Recommandations> RecommandationsSet { get; set; }
        public virtual DbSet<ProduitCategory> ProduitCategories { get; set; }
        public virtual DbSet<Produit> Produits { get; set; }
        public virtual DbSet<Localisation> Localisations { get; set; }
        public virtual DbSet<Canton> Cantons { get; set; }
        public virtual DbSet<Activite> Activites { get; set; }
        public virtual DbSet<Evenement> Evenements { get; set; }
        public virtual DbSet<Competence> Competences { get; set; }
    }
}
